### ISSUE TITLE
你好，我在运行“HeatGasPowerCombination.m”时报错，说“未定义函数或变量 'idx_bus'”，请问能帮忙看一下吗，十分感激！

### ISSUE THREAD

**Issue by 2226123114** [Wang-Yanping1996/Mixed-Heat-Gas-Power-System-Scheduling#2]
![image](https://user-images.githubusercontent.com/96046064/145776796-0e84e721-90ed-4934-b9bb-1074fec87a92.png)

-

**Comment by Wang-Yanping1996** [comment]
是否更改过项目的目录结构？可以把你电脑上这个项目的目录结构发给我吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wang-Yanping1996/Mixed-Heat-Gas-Power-System-Scheduling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 下午4:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Wang-Yanping1996/Mixed-Heat-Gas-Power-System-Scheduling] 你好，我在运行“HeatGasPowerCombination.m”时报错，说“未定义函数或变量 'idx_bus'”，请问能帮忙看一下吗，十分感激！ (Issue #2)





 

  

  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2226123114** [comment]
大佬有空解答一下吗？

**Comment by Wang-Yanping1996** [comment]
如果没修改过项目结构，可以看看存放路径是否有中文，如果有，放在全英文路径看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月17日(周五) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wang-Yanping1996/Mixed-Heat-Gas-Power-System-Scheduling] 你好，我在运行“HeatGasPowerCombination.m”时报错，说“未定义函数或变量 'idx_bus'”，请问能帮忙看一下吗，十分感激！ (Issue #2)




 
大佬有空解答一下吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
